### ISSUE TITLE
Wrong hearts on save file when using PAL save on NTSC

### ISSUE THREAD

**Issue by Agusum** [jgazeley/zelda#1]
Hi, the tool you created works great. Thank you so much!

I had a PAL OOT save and used it on an NTSC game. When doing this, the name changes to Japanese characters and the hearts being shown in the save file are always maxed, even if I don't have full hearts in game. Using your program I'm able to fix the name thing but the hearts problem is still occurring. Do you know what is causing it and how I can resolve it?

Thanks!

Original PAL save:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/4369698/178246002-4369d681-b052-4c3e-9bd6-d97b2c6a72d8.png">

Using the PAL save directly in NTSC:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/4369698/178246733-bb0f57ea-a859-4929-8739-66464a32da8c.png">

Changing name in file using your program:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/4369698/178246349-85924ddb-769d-4724-aed4-d191965518d5.png">

**Comment by jgazeley** [comment]
Hey there, sorry for the delay. I do know there's a hex value you can edit to change your hearts, but I'm not sure why changing your save from PAL to NTSC is causing that to change. Have you noticed any other changes to your save besides the hearts? Have you checked item counts or any thing like that.

**Comment by Agusum** [comment]
Hey, thanks for the reply. All the item count in game are the same, and even the hearts appear correctly when loading the game, it’s just that in the save selection screen they’re always maxed. Even if I lose extra hearts in game and save, the file will always show them full.

**Comment by jgazeley** [comment]
> Hey, thanks for the reply. All the item count in game are the same, and even the hearts appear correctly when loading the game, it’s just that in the save selection screen they’re always maxed. Even if I lose extra hearts in game and save, the file will always show them full.

Does the discrepancy appear to be related to converting from PAL to NTSC? Or do you suspect my tool has a bug that is modifying the way the file is displayed? Just want to be sure, I have to look over the code for this again but I don't think the tool is capable of adjusting anything besides the character name and the checksum.

**Comment by Agusum** [comment]
The discrepancy comes from the PAL to NTSC conversion. I just thought you could know what causes it since you created this tool and seemed to be an expert of the hexfile editing 🙂
